baseURL = "https://timewarrior.net"
languageCode = "en-us"
title = "Timewarrior"
theme = "bootstrap"
publishDir = "html"
disableKinds = ['taxonomy', 'term']

[params]
description = "Timewarrior is Free and Open Source Software that tracks time from the command line."

[security]
    [security.exec]
        allow = ['^asciidoctor$']
