[build]
publish = "html"
command = """\
  rm -fv Gemfile.lock \
  && gem install asciidoctor \
  && git submodule update -f --init \
  && hugo --gc --minify \
  """

[build.environment]
HUGO_VERSION = "0.118.2"
BUNDLE_FLAGS = "--no-deployment --path vendor/bundle"

[context.production.environment]
HUGO_VERSION = "0.118.2"

[context.branch-deploy.environment]
HUGO_VERSION = "0.118.2"
