name: My Target Workflow

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.sha }}

      # Add your workflow steps here

      - name: Extract Service Name, Version, and Changed Files
        run: |
          service_name=${{ github.event.client_payload.service }}
          echo "Service Name: $service_name"

          version=${{ github.event.client_payload.version }}
          echo "Version: $version"

          changed_filenames=${{ github.event.client_payload.changed_filenames}}
          echo "Changed files: $changed_filenames"

          encoded_file_contents=${{ github.event.client_payload.encoded_file_contents}}
          echo "Encoded file contents: $encoded_file_contents"