name: My Target Workflow

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.sha }}

      # Add your workflow steps here

      - name: Extract Service Name, Version, and Changed Files
        run: |
          service_name=${{ github.event.client_payload.service }}
          echo "Service Name: $service_name"

          version=${{ github.event.client_payload.version }}
          echo "Version: $version"

          python3 -m venv /tmp/venv
          /tmp/venv/bin/pip install --upgrade pip
          /tmp/venv/bin/pip install -r bin/requirements.txt

          echo "${{ toJson(github.event.client_payload) }}" > /tmp/venv/bin/doc-changes.json

          cat /tmp/venv/bin/doc-changes.json

          # /tmp/venv/bin/python bin/update-docs.py tmp/venv/bin/doc-changes.json

      # - name: Create Pull Request
      #   id: cpr
      #   uses: peter-evans/create-pull-request@v6
      #   with:
      #     delete-branch: true
      #     commit-message: Updated timewarrior docs
      #     author: "Timewarrior Docs Bot <timew-docs-bot@users.noreply.github.com>"
      #     title: Updated timewarrior docs
      #     body: |
      #       - Updated timewarrior docs

      #       Auto-generated by [create-pull-request][1]

      #       [1]: https://github.com/peter-evans/create-pull-request
      #     branch: update-tools
      # - name: Merge Pull Request
      #   if: "${{ steps.cpr.outputs.pull-request-number != '' }}"
      #   uses: juliangruber/merge-pull-request-action@v1
      #   with:
      #     github-token: ${{ secrets.PAT }}
      #     number: ${{ steps.cpr.outputs.pull-request-number }}
      #     method: merge
