name: My Target Workflow

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.sha }}

      # Add your workflow steps here

      - name: Extract Service Name, Version, and Changed Files
        run: |
          service_name=${{ github.event.client_payload.service }}
          echo "Service Name: $service_name"

          version=${{ github.event.client_payload.version }}
          echo "Version: $version"

          file_contents_json=${{ github.event.client_payload.file_contents_json}}
          echo "Changed files with content: $file_contents_json"